# Generated by Django 3.2.25 on 2024-06-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actionResult',
            field=models.TextField(blank=True, null=True),
        ),
    ]
